#!/bin/bash

str=`zenity --title "Supprimer en fin de nom de fichier" --entry --text "Chaîne de caractères à supprimer :"`

IFS=$'\n'

nbfiles=0
for file in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
do
    let nbfiles+=1
done
unit=`expr 100 / $nbfiles`

i=0
for file in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
do
#    zenity --info --text "mv $file ${file%$str}"
    mv "$file" "${file%$str}"
    let i+=unit
    echo $i
done | zenity --progress --auto-close
