#!/bin/bash

if [ $? -ne 0 ]; then
  exit
fi

IFS=$'\n'

nbfiles=0
for file in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
do
    let nbfiles+=1
done
unit=`expr 100 / $nbfiles`

i=0
for file in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
do
    dirname=`dirname $file`
    basename=`basename $file .wav`
    newfile=$dirname/${basename#$str}.mp3

    lame -V 9 --resample 22.05 $file $newfile

    let i+=unit
    echo $i
done | zenity --progress --auto-close
