#!/bin/bash

#str=`zenity --title "Ajouter date en début de nom de fichier" --entry --text "Chaîne à ajouter :"`

IFS=$'\n'

nbfiles=0
for file in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
do
    let nbfiles+=1
done
unit=`expr 100 / $nbfiles`

i=0

for file in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
do
    exiv2 rename -r "%Y%m%d_%H%M%S_:basename:" $file
#    mv "$file" "`dirname ${file}`/${str}`basename ${file}`"
    let i+=unit
    echo $i
done | zenity --progress --auto-close
